load(
    "//src/test_target_harness/Infra:test_target_harness.bzl",
    "test_target_harness",
)

test_target_harness(
    name = "Example",
    test_cases_per_target = 100,
    test_target_count = 10,
)
